#!/bin/bash


rm -f CMakeCache.txt

SOURCE=$HOME/ngc/portage

export ARCHOS="`uname -m`_`uname -s`"
# test 123
# modify the paths that point to the location of the
# installation directories below

cmake \
  -D CMAKE_C_COMPILER=`which mpicc` \
  -D CMAKE_CXX_COMPILER=`which mpiCC` \
  -D CMAKE_BUILD_TYPE=Debug \
  -D ENABLE_UNIT_TESTS=True \
  -D ENABLE_MPI=True \
  -D ENABLE_MPI_CXX_BINDINGS=True \
  -D Jali_DIR:FILEPATH=${HOME}/ngc/jali/install/lib \
  ${SOURCE}

