mkdir build

cd build

cmake \
  -D CMAKE_BUILD_TYPE=Debug \
  -D ENABLE_MPI=True \
  -D ENABLE_APP_TESTS=True \
  -D ENABLE_UNIT_TESTS=True \
  -D ENABLE_MPI_CXX_BINDINGS=True \
  -D Jali_DIR:FILEPATH=$JALI_INSTALL_PREFIX/lib \
  -D TANGRAM_DIR:FILEPATH=$TANGRAM_INSTALL_PREFIX \
  -D XMOF2D_DIR:FILEPATH=$XMOF2D_INSTALL_PREFIX/lib\
  -D PC_LAPACKE_NCLUDE_DIRS=$LAPACKE_INCLUDE_DIR \
  -D PC_LAPACKE_LIBRARY_DIRS=$LAPACKE_LIBRARY_DIR \
  -D ENABLE_THRUST=True \
  ..

make -j12
