# Blacklist
branches:
  except:
    - gh-pages

# Dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - mkdir build
  - cd build
  - cmake -D ENABLE_DOXYGEN=True ..
  - make doxygen

after_success:
  - cd $TRAVIS_BUILD_DIR
  - mkdir code_docs
  - cd code_docs
  - git clone -b gh-pages https://git@github.com/laristra/portage.git  

#  - chmod +x generateDocsAndDeploy.sh
#  - ./generateDocsAndDeploy.sh